#!/usr/sbin/nft -f

flush ruleset

table netdev filter {
    chain ingress {
        type filter hook ingress device enx001e063686b2 priority 0; policy accept;
        meta protocol {0x8912, 0x88e1} drop
    }
}

table inet filter {
  set local_nets {
    type ipv4_addr; flags interval; elements = { 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.0/8 }
  }
  chain input {
    type filter hook input priority 0; policy accept;
    meter per_src { ip saddr limit rate over 20/minute burst 10 packets } meta l4proto tcp tcp dport { 8080, 1443 } ct state new ip saddr != @local_nets log prefix "burst: " snaplen 0 counter
  }
}
